### PR TITLE
Added a darkened version of the char set (better on eyes) and made line 3 in cpu-circuit.circ a comment

### PR DESCRIPTION
**Pull request by kailando**
Now the new char sheet just needs to be implemented. _(I don't know how to use any of these languages, I'm a Python programmer)_

### CODE REVIEW

**Comment by sam-astro** [comment]
The character set defined in the image is read as binary (white is 1, black is 0). There is no color data stored, this would just fail to load in. But the characters can have custom colors, that is just set in memory. This feature was only added in version `v3.0.0-alpha` though, and that is still a dev build so it would make sense if you did not know.

**Comment by kailando** [comment]
Is there a way we can add RGB data to the bitmap? Maybe change how it
stores pixels to add RGB and maybe A?

**Comment by kailando** [comment]
Is there a way we can add RGB data to the bitmap? Maybe change how it stores pixels to add RGB and maybe A?

**Comment by kailando** [comment]
> The character set defined in the image is read as binary (white is 1, black is 0). There is no color data stored, this would just fail to load in. But the characters can have custom colors, that is just set in memory. This feature was only added in version `v3.0.0-alpha` though, and that is still a dev build so it would make sense if you did not know.

Is there a way we can add RGB data to the bitmap? Maybe change how it stores pixels to add RGB and maybe A?

**Comment by sam-astro** [comment]
I may be overthinking this, but is there any reason to need that functionality? As I said, you can change any characters' color in the newest dev version. 
Here is what this looks like in application: [https://www.youtube.com/live/ZLmCs6jb55U?si=7aAniZp07srSdjIT&t=148](https://www.youtube.com/live/ZLmCs6jb55U?si=7aAniZp07srSdjIT&t=148)

**Pull request closed without merging**
