### PR TITLE
Formatting Documentation

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-4b781e?style=for-the-badge&logoColor=white&logo=GitHub&labelColor=609926
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-9e122a?style=for-the-badge&logoColor=white&logo=GitLFS&labelColor=D81939
[Badge GitHub]: https://img.shields.io/badge/ＧｉｔＨｕｂ_Ｎｅｗｃｏｍｅｒｓ-be2e47?style=for-the-badge&logoColor=white&logo=BitWarden&labelColor=FD3A5C
[Badge Robot]: https://img.shields.io/badge/Ｉ＇ｍ_Ｈｕｍａｎ-8c3b63?style=for-the-badge&logoColor=white&logo=RuboCop&labelColor=c84f8c
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-4e2760?style=for-the-badge&logoColor=white&logo=AskUbuntu&labelColor=73398D
[Badge Info]: https://img.shields.io/badge/Ｉｎｆｏｒｍａｔｉｏｎ-01434e?style=for-the-badge&logoColor=white&logo=InternetArchive&labelColor=006272

[Button MarkedDown]: https://img.shields.io/badge/MarkedDown-00b2ff?style=for-the-badge&logoColor=white&logo=Markdown

[License Badges]: https://github.com/MarkedDown/Licenses
[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md
[Wiki]: https://github.com/MarkedDown/Wiki
[MarkedDown]: https://github.com/MarkedDown 'How to better use Markdown'

<br>
<br>

<div align = center>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

</div>
  
<br>
<br>

## ![Badge Suggestions]

  <br>

- ***[Disable unused Widgets][Widgets]***:

  - `Packages`

  <br>

- ***[Disable unused Tabs][Tabs]***:

  - `Projects`

  - `Actions`

  - `Wiki`
  
  <br>

- Add graphics from the video for visualization

<br>
<br>

## ![Badge Changes]

*As this is a draft, the changes list will,.. change.*

- General formatting / spacing

- Separated topics

- Added quicklinks

- Added license badge

- Linked YouTube video

   *There isn't a official playlist yet..*

- Formatted topics:
 
  - Building

  - Installation

  - Programming

  - Armstrong
  
  - Memory Layout

  - Instruction Set

  - Micro Instructions (Only Basic Formatting)

<br>
<br>

## ![Badge Ask]

- ***If you have any questions.***

- ***In case you do not agree with some of the changes made in this PR***,
  *please first let me know about them, before disregarding it entirely so*
  *we can possibly find a middle ground and have it not go to waste.*

<br>
<br>

## ![Badge Info]

If you want to know more about **Markdown** check out:

<br>

                            [![Button MarkedDown]][MarkedDown]

<br>
<br>

[Preview]: https://github.com/ElectronicsArchiver/Astro8-Computer

### CODE REVIEW

**Comment by ElectronicsArchiver** [comment]
@sam-astro Please review this PR

**Comment by swift502** [comment]
The preview looks quite confusing to me. Why not use GitHub wikis or something like mkdocs?

**Comment by ElectronicsArchiver** [comment]
***[Why not to use GitHub Wiki][Wiki]***


[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-4b781e?style=for-the-badge&logoColor=white&logo=GitHub&labelColor=609926
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-9e122a?style=for-the-badge&logoColor=white&logo=GitLFS&labelColor=D81939
[Badge GitHub]: https://img.shields.io/badge/ＧｉｔＨｕｂ_Ｎｅｗｃｏｍｅｒｓ-be2e47?style=for-the-badge&logoColor=white&logo=BitWarden&labelColor=FD3A5C
[Badge Robot]: https://img.shields.io/badge/Ｉ＇ｍ_Ｈｕｍａｎ-8c3b63?style=for-the-badge&logoColor=white&logo=RuboCop&labelColor=c84f8c
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-4e2760?style=for-the-badge&logoColor=white&logo=AskUbuntu&labelColor=73398D
[Badge Info]: https://img.shields.io/badge/Ｉｎｆｏｒｍａｔｉｏｎ-01434e?style=for-the-badge&logoColor=white&logo=InternetArchive&labelColor=006272

[Button MarkedDown]: https://img.shields.io/badge/MarkedDown-00b2ff?style=for-the-badge&logoColor=white&logo=Markdown

[License Badges]: https://github.com/MarkedDown/Licenses
[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md
[Wiki]: https://github.com/MarkedDown/Wiki
[MarkedDown]: https://github.com/MarkedDown 'How to better use Markdown'

**Comment by ElectronicsArchiver** [comment]
> The preview looks quite confusing to me. 

What about buttons is confusing you?

**Comment by ElectronicsArchiver** [comment]
Would look better with

> Add graphics from the video for visualization

**Comment by ElectronicsArchiver** [comment]
Btw, have you even checked the documetation or have you only looked at the README?

**Comment by sam-astro** [comment]
I like the work you did, but I don't really like traversing the documentation with a file structure. It is a lot neater and easier to move around when using the wiki format.

**Comment by ElectronicsArchiver** [comment]
> I like the work you did, but I don't really like traversing the documentation with a file structure. It is a lot neater and easier to move around when using the wiki format.

What do you mean 'file structure', that's what the buttons are for?

'Wiki format'? A sidebar that is just links / buttons as well?

**Comment by sam-astro** [comment]
Yes, but in a wiki, all of the pages are visible at once. But when browsing files using Github online, you can only see what is directly in the folder you are currently in. This just seems like it will make finding a specific page a lot more tedious than it needs to be.

**Comment by ElectronicsArchiver** [comment]
1. I'd argue no, looking at it from the other side, having 'all of the pages are visible at once' is one of the worst ways to find what you are looking for.

2. You could add a top bar with the main topics so one can easily switch between them.

**Comment by sam-astro** [comment]
Pages like this, that work as simple dropdowns and are easily navigatable through all of the topics mentioned would be much easier, combing through a file tree can't even compare. There is even a search.
image

**Comment by ElectronicsArchiver** [comment]
How about utilizing both, use the wikis custom sidebar and still retain the documentation in folders so you can have your overview / search and have people be able to contribute to them.

**Comment by sam-astro** [comment]
Oh I honestly didn't know you could do that. I guess I could try it, that would make sense.

**Comment by ElectronicsArchiver** [comment]
I could design a sidebar if you want.

Regardless, your concerns don't stop
my PR in general though, you said you
liked that part right?

So that could be handeled separately?

**Comment by sam-astro** [comment]
Yes, I like how you divided and formatted the contents. I think if you do a simple integration with wiki I could handle the rest of any changes myself and merge this PR.

**Comment by ElectronicsArchiver** [comment]
> I think if you do a simple integration with wiki 

Well again, I can design & post a sidebar, but I'm 
not able to edit wiki content as a contributor.

One can disable the 'only team' restriction for wikis
however I don't know what permissions it then has, nor
is it connected to the repository itelsef.

( Wiki content is not part of the repository itself )
( Which makes contributing / attributing a pain )

**Comment by sam-astro** [comment]
Can you make a sidebar that is dynamic and with a search feature like the wiki? I just think using the already created system would be easier

**Comment by ElectronicsArchiver** [comment]
No I'm talking about the wiki custom sidebar, you can just customize it's content.

**Comment by EmeraldCraft34** [comment]
I really like how it's set up (file, github wiki, or otherwise). Very creative. In my opinion, I think a wiki would be better for documentation mostly because it just requires a click (and maybe some typing) to get where you need. 

Again, that's just my opinion, not everyone will agree, but, anyways, the documentation looks nice!

Another thing I see (with stuff like Py65) is that the developers will host the documentation on a completely different platform, such as Read the Docs.

**Comment by ElectronicsArchiver** [comment]
Right, you could just point a GitHub Pages site to the Documentation folder as well and configure a sidebar to be generated.

**Comment by sam-astro** [comment]
> I really like how it's set up (file, github wiki, or otherwise). Very creative. In my opinion, I think a wiki would be better for documentation mostly because it just requires a click (and maybe some typing) to get where you need.
> 
> Again, that's just my opinion, not everyone will agree, but, anyways, the documentation looks nice!
> 
> Another thing I see (with stuff like Py65) is that the developers will host the documentation on a completely different platform, such as Read the Docs.

True, for any large project I think Read the Docs is the best option.

**Comment by ElectronicsArchiver** [comment]
https://jekyllthemes.io/theme/just-the-docs

**Comment by ElectronicsArchiver** [comment]
Has everthing you asked for and literally only needs 

```yaml
remote_theme: just-the-docs/just-the-docs
```

to be added to the pages config

**Comment by sam-astro** [comment]
I thought github pages requires a different repository?

**Comment by EmeraldCraft34** [comment]
> I thought github pages requires a different repository?

You can make a separate tree just for github pages.

**Comment by ElectronicsArchiver** [comment]
No, it can be used on any repo.

It requires to either use the root of the project or a `/docs/` folder.
Thats why it often is useful to make a separate branch or repo for it.

**Comment by sam-astro** [comment]
Ok, do you know how to implement that? I think it would probably be the best option then

**Comment by ElectronicsArchiver** [comment]
Well for basic steps, you simply
need to activate GitHub pages in
the repository settings.

In the `Pages` settings you will have to activate
it and I guess for now select `root` for it.

I could check out the config options 
and append it to the PR if you want.

**Comment by EmeraldCraft34** [comment]
Here's what I would do:

- Make a github pages website
- Create a branch on this repo just for github pages
- Enable github pages on this repo
- You could access it at sam-astro.github.com/Astro8-Computer or what ever url you set it to.

**Comment by ElectronicsArchiver** [comment]
@EmeraldCraft34 considering this PR, I wouldn't create a branch right away

**Comment by ElectronicsArchiver** [comment]
@EmeraldCraft34 pages are hosted at <username>.github.io/<repo>

**Comment by ElectronicsArchiver** [comment]
> Make a github pages website

This step doesn't exist since the GitHub page can
just host the markdown files as html with jerkyl.

**Comment by EmeraldCraft34** [comment]
I think we should either leave it on the github repo for easy access or move it to a github pages site. Both use markdown anyways, so if we wanted to we could even do both.

The documentation will take some time to grow. Depending on it, we can probably figure it out soon.

**Comment by ElectronicsArchiver** [comment]
@EmeraldCraft34 Well for now, it should stay in the repo and aftwards that can be adjusted..

**Comment by EmeraldCraft34** [comment]
Yes, that'll make it easier to move over to another wiki setup once it is finished in the repo. I'm guessing you're able to move the files over from the repo into pages?

**Comment by ElectronicsArchiver** [comment]
Not sure what you mean, GitHub Pages uses the repos file directly, no need to more anything for now..

**Comment by EmeraldCraft34** [comment]
Sorry, I had a brain error, I think I understand now.

**Comment by ElectronicsArchiver** [comment]
@sam-astro With the github pages approach the PR could be merged already..

I don't want to experiment on the done documentation.
( And not have to rebase + manual fixup again, for the third time )

**Comment by ElectronicsArchiver** [comment]
Thank you~

**Comment by sam-astro** [comment]
Thanks for your contributions!

**Pull request merged**
